#!/bin/bash

red="RED"
gre="GREEN"
blu="BLUE"

sum0=0
sum1=0
sum2=0

res="null"
SECONDS=0

for i in {0..9}
do
    echo "epoch $((i))"
    nohup java -Djava.library.path=lib/native -jar repo/htw/ai/lenz/sarg-server/3.0/sarg-server-3.0.jar 4 headless > log 2>&1 &
    java -jar target/SargClient.jar 127.0.0.1 ${red} 1 > /dev/null 2>&1 &
    java -jar target/SargClient.jar 127.0.0.1 ${gre} 2 > /dev/null 2>&1 &
    java -jar target/SargClient.jar 127.0.0.1 ${blu} 3 > /dev/null 2>&1 &
    wait
    res=$(tail -3 log)
#    printf '\t%s\n' $res
    if grep -owq "$red: 5" <<< "$res"; then ((sum0++)); fi
    if grep -owq "$gre: 5" <<< "$res"; then ((sum1++)); fi
    if grep -owq "$blu: 5" <<< "$res"; then ((sum2++)); fi
done

printf 'final result: %s=%d %s=%d %s=%d\n' $red $sum0 $gre $sum1 $blu $sum2
printf 'run time: %d h %d min %d sec\n' $[SECONDS/3600] $[SECONDS/60] $[SECONDS%60]

