#!/bin/bash

# output="$(java -Djava.library.path=lib/native -jar sarg.jar 400 900 700 showcoords)"
# output="$(java -Djava.library.path=lib/native -jar sarg.jar 4 headless)"
# nohup java -Djava.library.path=lib/native -jar sarg.jar 4 headless > log 2>&1 &
nohup java -Djava.library.path=../sarg2/lib/native -jar ../sarg2/sarg.jar 4 headless > log 2>&1 &
printf('start server')

java -jar jar/SargClient.jar 127.0.0.1 one 1 > /dev/null 2>&1 &
java -jar jar/SargClient.jar 127.0.0.1 abeta 2 > /dev/null 2>&1 &
java -jar jar/SargClient.jar 127.0.0.1 three 3 > /dev/null 2>&1 &

printf('ans:\n')
cat log
# echo $output
